import {
	darkThemeBase as baseThemeDark,
	lightThemeBase as baseThemeLight,
} from '../../base/paradigmMobile';

export const lightColors = {
	...baseThemeLight.colors,

	mailappColorAndroidFrameFocus: '#ff9e00',
	mailappColorAndroidPopupShadowAmbient: '#969696',
	mailappColorAndroidPopupShadowSpot: 'rgba(0, 0, 0, 0.5)',
	mailappColorAndroidRipple: 'rgba(0, 0, 0, 0.25)',
	mailappColorAndroidRippleContrast: 'rgba(255, 255, 255, 0.5)',
	mailappColorAndroidRipplePromo: 'rgba(255, 169, 48, 0.85)',
	mailappColorAndroidToolbarShadowStart: 'rgba(0, 0, 0, 0.06)',
	mailappColorAndroidToolbarShadowEnd: baseThemeLight.colors.colorTransparent,

	mailappColorAttachApkIcon: '#00660A',
	mailappColorAttachBookIcon: '#7D7F80',
	mailappColorAttachCalendarBackground: '#b684c3',
	mailappColorAttachDefaultBackground: '#c8cbcc',
	mailappColorAttachDoсIcon: '#3955B8',
	mailappColorAttachDocBackground: '#6cb8f3',
	mailappColorAttachEmlBackground: '#6cb8f3',
	mailappColorAttachEpubBackground: '#6cb8f3',
	mailappColorAttachHtmlIcon: '#007062',
	mailappColorAttachImgBackground: '#58be6c',
	mailappColorAttachImgIcon: '#006609',
	mailappColorAttachMovieBackground: '#fc2c38',
	mailappColorAttachMovieIcon: '#992112',
	mailappColorAttachMusicBackground: '#ff982a',
	mailappColorAttachMusicIcon: '#BE4300',
	mailappColorAttachPassbookBackground: '#6cb8f3',
	mailappColorAttachPassbookIcon: '#3955B8',
	mailappColorAttachPdfBackground: '#f96657',
	mailappColorAttachPdfIcon: '#992112',
	mailappColorAttachPptBackground: '#ff982a',
	mailappColorAttachPptIcon: '#BE4300',
	mailappColorAttachTxtBackground: '#69b9b1',
	mailappColorAttachTxtIcon: '#007062',
	mailappColorAttachUnknownIcon: '#000000',
	mailappColorAttachXlsBackground: '#58be6c',
	mailappColorAttachXlsIcon: '#000000',
	mailappColorAttachZipBackground: '#ffca5a',
	mailappColorAttachZipIcon: '#BE6200',

	mailappColorAuthorizationGmailBackgroundGradientEnd: '#9B0F01',
	mailappColorAuthorizationGmailBackgroundGradientMiddle: '#D54E41',
	mailappColorAuthorizationGmailBackgroundGradientStart: '#FE7C38',
	mailappColorAuthorizationMailBackgroundGradientEnd: '#4585FE',
	mailappColorAuthorizationMailBackgroundGradientMiddle: '#1447D2',
	mailappColorAuthorizationMailBackgroundGradientStart: '#512BC9',
	mailappColorAuthorizationOutlookBackgroundGradientEnd: '#0C1691',
	mailappColorAuthorizationOutlookBackgroundGradientMiddle: '#0072C6',
	mailappColorAuthorizationOutlookBackgroundGradientStart: '#16B9FE',
	mailappColorAuthorizationYahooBackgroundGradientEnd: '#1447D2',
	mailappColorAuthorizationYahooBackgroundGradientMiddle: '#512BC9',
	mailappColorAuthorizationYahooBackgroundGradientStart: '#4585FE',
	mailappColorAuthorizationYandexBackgroundGradientEnd: '#FF0303',
	mailappColorAuthorizationYandexBackgroundGradientMiddle: '#F06C43',
	mailappColorAuthorizationYandexBackgroundGradientStart: '#F6BF5E',

	mailappColorAvatarDeselectedOverlay: '#FFFFFF',
	mailappColorAvatarSelectedOverlay: '#005FF9',
	mailappColorBackgroundAccentGradientEnd: 'rgba(0, 95, 249, 0.08)',
	mailappColorBackgroundAccentGradientStart: 'rgba(0, 95, 249, 0.16)',
	mailappColorBackgroundCallsButtonSecondaryAlpha:
		'rgba(255, 255, 255, 0.12)',
	mailappColorBackgroundCallsContent: '#191919',
	mailappColorBackgroundCallsSecondary: 'rgba(255, 255, 255, 0.12)',
	mailappColorBackgroundGradientEnd: 'rgba(0, 0, 0, 0)',
	mailappColorBackgroundGradientStart: '#ffffff',
	mailappColorBackgroundNegativeGradientEnd: 'rgba(255, 38, 0, 0.08)',
	mailappColorBackgroundNegativeGradientStart: 'rgba(255, 38, 0, 0.16)',
	mailappColorBackgroundPlaceholder: '##F0F1F3',
	mailappColorBackgroundSecondaryAlpha: 'rgba(0, 16, 61, 0.06)',
	mailappColorBrand: '#005FF9',

	mailappColorCategoryEvents: '#3BBAFE',
	mailappColorCategoryFees: '#E60000',
	mailappColorCategoryFinance: '#2FC885',
	mailappColorCategoryMailings: '#FC8A15',
	mailappColorCategoryNews: '#08ABD9',
	mailappColorCategoryOrder: '#FF54AA',
	mailappColorCategoryPromo: '#005FF9',
	mailappColorCategoryRegistration: '#FF9E00',
	mailappColorCategorySocial: '#7288FF',
	mailappColorCategoryToMyself: '#00BD93',
	mailappColorCategoryTravel: '#BA34FC',

	mailappColorCheckboxBackground: baseThemeLight.colors.colorBackgroundAccent,
	mailappColorFloatingButtonOverlayAlpha: 'rgba(255, 255, 255, 0.5)',

	mailappColorHeaderBackgroundAccent: '#005FF9',
	mailappColorHeaderBackgroundSecondary: '#f0f0f0',
	mailappColorHeaderBadge: '#005FF9',
	mailappColorHeaderCallsBackground: '#191919',
	mailappColorHeaderEditText: '#005FF9',
	mailappColorHeaderFilterMode: '#999999',
	mailappColorHeaderIconPrimary: '#474747',
	mailappColorHeaderIconUnread: '#005FF9',
	mailappColorHeaderTextPrimary: '#1E1E1E',
	mailappColorHeaderTextSecondary: '#87898F',
	mailappColorHeaderThemedBackgroundAccent: '#FFFFFF',
	mailappColorHeaderThemedIcon: '#FFFFFF',
	mailappColorHeaderThemedIconAccent: '#FFFFFF',
	mailappColorHeaderThemedIconPrimary: '#FFFFFF',
	mailappColorHeaderThemedTextPrimary: '#FFFFFF',
	mailappColorHeaderThemedTextSecondary: 'rgba(255, 255, 255, 0.7)',

	mailappColorIconAttachImage: '#006609',
	mailappColorIconAttachVideo: '#992112',
	mailappColorIconFlag: '#FC2C38',
	mailappColorIconGoogleAds: '#ffc311',
	mailappColorIconUnread: '#005FF9',
	mailappColorImageGradientStart: 'rgba(0, 0, 0, 0.95)',
	mailappColorImagePlaceholder:
		baseThemeLight.colors.colorBackgroundSecondary,
	mailappColorKeyboardBackground: '#e0e0e0',
	mailappColorKeyboardPanelBackground: '#BBC2CA',
	mailappColorListBackground: '#FFFFFF',
	mailappColorVkConnectBackground: '#4986CC',
	mailappColorMarusiaBubbleBackground: '#FFFFFF',
	mailappColorOverlaySecondary: 'rgba(0, 0, 0, 0.3)',

	mailappColorPlateButtonTextDark: baseThemeLight.colors.colorTextPrimary,
	mailappColorPlateButtonTextLight: baseThemeDark.colors.colorTextPrimary,
	mailappColorPlateDarkBackground: '#E0ECFF',
	mailappColorPlateDarkButtonBackgroundPrimary: '#0B66F9',
	mailappColorPlateDarkButtonBackgroundSecondary: 'rgba(255, 255, 255, 0.9)',
	mailappColorPlateDarkIcon: baseThemeDark.colors.colorIconPrimary,
	mailappColorPlateDarkIconBackground: 'rgba(0, 0, 0, 0.48)',
	mailappColorPlateDarkTextPrimary: baseThemeDark.colors.colorTextPrimary,
	mailappColorPlateLightBackground: 'rgba(0, 16, 61, 0.06)',
	mailappColorPlateLightButtonBackgroundPrimary: '#005FF9',
	mailappColorPlateLightButtonBackgroundSecondary: 'rgba(255, 255, 255, 0.9)',
	mailappColorPlateLightIcon: baseThemeLight.colors.colorIconPrimary,
	mailappColorPlateLightIconBackground: 'rgba(255, 255, 255, 0.48)',
	mailappColorPlateLightTextPrimary: baseThemeLight.colors.colorTextPrimary,

	mailappColorProjectAddressBookAccent: '#4C9BD9',
	mailappColorProjectAddressBookBackground: '#4C9BD9',
	mailappColorProjectBonusBackground: '#005FF9',
	mailappColorProjectCalendarAccent: '#005FF9',
	mailappColorProjectCallsAccent: '#38E0A1',
	mailappColorProjectCallsBackground: '#E1FBF2',
	mailappColorProjectCleanmasterBackground: '#4C9BD9',
	mailappColorProjectCloudAccent: '#005FF9',
	mailappColorProjectCloudBackground: '#005FF9',
	mailappColorProjectFinesBackground: '#E60000',
	mailappColorProjectPaymentBackground: '#2D9CF6',
	mailappColorProjectPaymentsAccent: '#2D9CF6',
	mailappColorProjectTasksAccent: '#005FF9',
	mailappColorProjectTodoAccent: '#005FF9',
	mailappColorProjectTodoBackground: '#005FF9',

	mailappColorPromoBadge: '#0ADC6C',
	mailappColorQuickActionPrimaryIcon: baseThemeLight.colors.colorIconAccent,
	mailappColorQuickActionPrimaryText: baseThemeLight.colors.colorTextAccent,
	mailappColorScannerBorder: '#ffdc30',
	mailappColorSeparatorContrastAlpha: 'rgba(255, 255, 255, 0.9)',
	mailappColorSeparatorPrimaryAlpha: 'rgba(0, 16, 61, 0.12)',
	mailappColorSettingsPersonalDataBackground: '#19A16E',
	mailappColorSettingsInfoBackground: '#36C5CD',
	mailappColorSettingsOtherRegularBackground: '#CCCED3',
	mailappColorSettingsSecurityBackground: '#46B88C',
	mailappColorSettingsSubscriptionsBackground: '#2D9CF6',
	mailappColorSettingsTasksBackground: '#FA8857',
	mailappColorSettingsViewBackground: '#EC9DCE',
	mailappColorSnackbarBackground: '#333333',
	mailappColorSnackbarButtonBackground: '#d8d8d8',
	mailappColorSnackbarTextAccent: '#6EA5FF',
	mailappColorSplashBackground: baseThemeLight.colors.colorBackgroundAccent,
	mailappColorSplashLogo: baseThemeLight.colors.colorIconContrast,
	mailappColorSwitchBackground: baseThemeLight.colors.colorBackgroundAccent,
	mailappColorTextSecondaryContrast: 'rgba(255, 255, 255, 0.48)',
	mailappColorTextUnread: baseThemeLight.colors.colorTextPrimary,
	mailappColorToolbarBackground: baseThemeLight.colors.colorBackgroundModal,
	mailappColorToolbarIcon: baseThemeLight.colors.colorIconAccent,
	mailappColorToolbarText: baseThemeLight.colors.colorTextAccent,
	mailappColorTrackBackground: baseThemeLight.colors.colorIconSecondary,
	mailappColorViewerBackground: '#000000',
	mailappColorViewerButtonBackground: 'rgba(50, 50, 50, 0.85)',
};

export const darkColors = {
	...lightColors,
	...baseThemeDark,

	mailappColorAuthorizationGmailBackgroundGradientEnd: '#360704',
	mailappColorAuthorizationGmailBackgroundGradientMiddle: '#1D0101',
	mailappColorAuthorizationGmailBackgroundGradientStart: '#B20000',
	mailappColorAuthorizationMailBackgroundGradientEnd: '#',
	mailappColorAuthorizationMailBackgroundGradientMiddle: '#',
	mailappColorAuthorizationMailBackgroundGradientStart: '#',
	mailappColorAuthorizationOutlookBackgroundGradientEnd: '#00274A',
	mailappColorAuthorizationOutlookBackgroundGradientMiddle: '#050F23',
	mailappColorAuthorizationOutlookBackgroundGradientStart: '#1B74B4',
	mailappColorAuthorizationYahooBackgroundGradientEnd: '#770066',
	mailappColorAuthorizationYahooBackgroundGradientMiddle: '#060222',
	mailappColorAuthorizationYahooBackgroundGradientStart: '#350386',
	mailappColorAuthorizationYandexBackgroundGradientEnd: '#33081D',
	mailappColorAuthorizationYandexBackgroundGradientMiddle: '#240713',
	mailappColorAuthorizationYandexBackgroundGradientStart: '#A81341',

	mailappColorBackgroundAccentGradientEnd: 'rgba(0, 95, 249, 0.2)',
	mailappColorBackgroundAccentGradientStart: 'rgba(0, 95, 249, 0.28)',
	mailappColorBackgroundNegativeGradientEnd: 'rgba(255, 38, 0, 0.2)',
	mailappColorBackgroundNegativeGradientStart: 'rgba(255, 38, 0, 0.28)',
	mailappColorBackgroundSecondaryAlpha: 'rgba(255, 255, 255, 0.16)',
	mailappColorBrand: '#0b66f9',

	mailappColorCategoryEvents: '#2DA9EB',
	mailappColorCategoryFees: '#E70101',
	mailappColorCategoryFinance: '#0EAB67',
	mailappColorCategoryMailings: '#DF770B',
	mailappColorCategoryNews: '#08ABD9',
	mailappColorCategoryOrder: '#D03784',
	mailappColorCategoryPromo: '#0b66f9',
	mailappColorCategoryRegistration: '#DE8A04',
	mailappColorCategorySocial: '#4F6DDC',
	mailappColorCategoryToMyself: '#00BD93',
	mailappColorCategoryTravel: '#A447D3',

	mailappColorCheckboxBackground: baseThemeDark.colors.colorBackgroundAccent,
	mailappColorFloatingButtonOverlayAlpha: 'rgba(0, 0, 0, 0.5)',

	mailappColorHeaderBackgroundAccent:
		baseThemeDark.colors.colorBackgroundAccent,
	mailappColorHeaderBackgroundSecondary: '#f0f0f0',
	mailappColorHeaderBadge: baseThemeDark.colors.colorIconAccent,
	mailappColorHeaderEditText: baseThemeDark.colors.colorTextAccent,
	mailappColorHeaderFilterMode: '#999999',
	mailappColorHeaderIconPrimary: '#eaeaea',
	mailappColorHeaderIconUnread: baseThemeDark.colors.colorIconAccent,
	mailappColorHeaderTextPrimary: '#eaeaea',
	mailappColorHeaderTextSecondary: '#8C8E94',
	mailappColorHeaderThemedBackgroundAccent: '#FFFFFF',
	mailappColorHeaderThemedIcon: 'rgba(255, 255, 255, 0.7)',
	mailappColorHeaderThemedIconAccent: '#FFFFFF',

	mailappColorIconFlag: '#CA0D00',
	mailappColorIconUnread: baseThemeDark.colors.colorIconAccent,
	mailappColorImagePlaceholder: baseThemeDark.colors.colorBackgroundSecondary,
	mailappColorListBackground: baseThemeDark.colors.colorBackgroundContent,
	mailappColorVkConnectBackground: '#4986CC',
	mailappColorMarusiaBubbleBackground: '#FFFFFF',

	mailappColorQuickActionPrimaryIcon: baseThemeDark.colors.colorIconAccent,
	mailappColorQuickActionPrimaryText: baseThemeDark.colors.colorTextAccent,
	mailappColorSeparatorContrastAlpha: 'rgba(255, 255, 255, 0.9)',
	mailappColorSeparatorPrimaryAlpha: 'rgba(7, 7, 7, 0.48)',
	mailappColorSettingsPersonalDataBackground: '#19A16E',
	mailappColorSettingsInfoBackground: '#21A1A9',
	mailappColorSettingsOtherRegularBackground: '#9599A3',
	mailappColorSettingsSecurityBackground: '#46B88C',
	mailappColorSettingsSubscriptionsBackground: '#248ECF',
	mailappColorSettingsTasksBackground: '#FA8857',
	mailappColorSettingsViewBackground: '#BE3A7F',
	mailappColorSplashBackground: baseThemeDark.colors.colorBackgroundAccent,
	mailappColorSplashLogo: baseThemeDark.colors.colorIconContrast,
	mailappColorSwitchBackground: baseThemeDark.colors.colorBackgroundAccent,
	mailappColorTextSecondaryContrast: 'rgba(245, 246, 255, 0.6)',
	mailappColorTextUnread: baseThemeDark.colors.colorTextPrimary,
	mailappColorToolbarBackground: baseThemeDark.colors.colorBackgroundModal,
	mailappColorToolbarIcon: baseThemeDark.colors.colorIconAccent,
	mailappColorToolbarText: baseThemeDark.colors.colorTextAccent,
	mailappColorTrackBackground: baseThemeDark.colors.colorIconSecondary,
};