name: 'Cron / Node Update'
on:
  schedule:
    - cron: '0 5 * * 1' # Runs at 05:00, only on Monday

jobs:
  node-update:
    name: Node update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node setup
        uses: ./.github/actions/node-setup

      - uses: VKCOM/gh-actions/shared/node/nvmrc-up-pr@main
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
